### ISSUE TITLE
VersionParser accepts and further corrupts badly formatted version string

### ISSUE THREAD

**Issue by simonberger** [composer/semver#106]
While playing around with the VersionParser I noticed that it accepts the following version

`1.0.0<1.0.5-dev` or also `1.0.0-dev<1.0.5-dev`

It fails on the version without the dev stability suffix but with -dev it works because of https://github.com/composer/semver/blob/master/src/VersionParser.php#L162

Subsequent code (for example generating `Intervals`) can't work correctly with the Constraint VersionParser produces but no error occurs.
On side of composer it just does not find a version for the package this kind of version is used on. This is the same in composer 1.10.X with semver 1.X
So for composer I consider this problem very minor.

My expectation is that it throws an error like it does without the dev stability.

**Comment by Seldaek** [comment]
Yeah essentially this is seen as a branch name (`1.0.0<1.0.5` and `1.0.0-dev<1.0.5` would be the branch name). But it should indeed not validate it as it's not numeric, only with a `dev-` prefix should it accept such random input.. I'll take a look.

**Comment by simonberger** [comment]
I missed an information in my post,
The problem is actually the missing spaces like `1.0.0-dev < 1.0.5-dev` which are essential for the parser to work
Parsing all other constraints missing the space fail with an error message. Just adding `-dev` nullifies that.

**Comment by Seldaek** [comment]
Think it's all good now, but please feel free to experiment some more. Always good to cover edge cases if it can be reasonably done.

**Comment by Seldaek** [comment]
4 releases of semver and 2 of composer later.. I think I'm done dealing with the fallout from this "minor" change 😅 

See https://github.com/composer/composer/issues/9191 and co for a good learning experience on "if it works don't touch it".

It's for the better in the long run tho, glad we validate more things correctly now.

**Comment by simonberger** [comment]
I'm sorry for your trouble.
In my opinion that shows how important a robust semver package is for composer. It shouldn't hold back any improvement. It also demonstrated how many really bad or at least dubious composer.json configs are out there to get the project requirements running in any possible way... ;)
Thanks for the insights and the fix !
