### ISSUE TITLE
Proposal: Move functions out of Intervals class

### ISSUE THREAD

**Issue by simonberger** [composer/semver#112]
`Intervals` class got really big and consists of functions of very different tasks. Out of blackbox view they also have not much to do with the idea of the Intervals class. Similarity is just using intervals internally.

I like to do the following changes:
- Move `compactConstraint` to new `Optimize` class
- Move `isSubsetOf` and `haveIntersections` to `Comparator`
- Set `generateIntervals` to public as it is used in haveInspections or solve that differently.

If you agree to this it should be done in a new major release. Otherwise we end up in duplicated code or cross references to deprecate the old functions.

**Comment by Seldaek** [comment]
IMO it's kinda ok as it is, the public API of the class isn't huge and all somewhat related to manipulating constraints. Maybe the classname isn't ideal, but given the few people interested in using this directly i don't really feel like these minor improvements warrant yet another major release. We can keep it open for consideration if anything else comes along requiring a major release tho.
