### ISSUE TITLE
 Invalid version string "CLX6_2020R01-dev" in "dev-code-refactory-for-better-readability as CLX6_2020R01-dev", the alias must be an exact version

### ISSUE THREAD

**Issue by staabm** [composer/semver#113]
with the 1.10.13 release of composer we see errors regarding invalid version strings, which did work perfectly before this release.

maybe we relied on undocumented behaviour, maybe there is some kind of regression going on.. lets discuss ;-).

we use composer constraints like
```
"my/package" : "dev-my-branch-name as dev-a-release-branch-name",
```

which worked before but now errors with
```
"complex/rocket" : "dev-code-refactory-for-better-readability as dev-CLX6_2020R01",
```
->
```
composer update
                                                                                                                                
  [UnexpectedValueException]                                                                                                                        
  Invalid version string "CLX6_2020R01-dev" in "dev-code-refactory-for-better-readability as CLX6_2020R01-dev", the alias must be an exact version 
```

ENV:

```
composer diagnose

Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.13
PHP version: 7.4.5
PHP binary path: C:\tools\php74\php.exe
OpenSSL version: OpenSSL 1.1.1e  17 Mar 2020
```

**Comment by Seldaek** [comment]
This should only error if the alias is in the root package though (which you can easily fix), and if the alias is invalid.

`dev-code-refactory-for-better-readability as CLX6_2020R01-dev` errors because it should be written as `dev-CLX6_2020R01` with the dev- prefix instead of the suffix (which is only allowed for numeric branches).

**Comment by staabm** [comment]
just verified, your suggestion works. in case this is a intentionall BC break, feel free to close.

**Comment by Seldaek** [comment]
Yeah it's by design, only fails on root composer.json where you can actually fix it rather easily, so hoping it's not causing too much trouble :)
