### ISSUE TITLE
dev-trunk vs. dev-master

### ISSUE THREAD

**Issue by clxmstaab** [composer/semver#115]
with the recent release its no longer possible to have a `dev-trunk` constraint (which we have from SVN times) but actually use a `dev-master` branch. it seems `dev-trunk` was a alias for `dev-master` which is no longer the case.

reproduced this issue with composer v2. is this a known/intentional BC break?

**Comment by stof** [comment]
in composer 1, `dev-trunk` and `dev-master` (and `dev-default`) were all normalized as `9999999-dev`. This indeed made them satisfy each other constraint, but probably not intentionally.
As this caused a lot of issue, especially when a branch alias was also defined, it was been removed from Composer 2.

**Comment by Seldaek** [comment]
That's right, intended break although I'll leave this open until it is documented more clearly in the upgrade guide.
