### ISSUE TITLE
Invalid version string for some default PHP version naming scheme

### ISSUE THREAD

**Issue by lcharette** [composer/semver#125]
We're currently using [the equivalent of this line of code](https://github.com/userfrosting/UserFrosting/blob/f393e23cc324041f34356ae0064a157095bf4b1a/app/sprinkles/core/src/Util/VersionValidator.php#L57) : 

```
$satisfies = Semver::satisfies(phpversion(), '^7.2');
```

Issue is, our CI returns this php version (which is technically invalid I know) : `7.2.34-18+ubuntu20.04.1+deb.sury.org+1`. So when running Unit/Feature Tests [CI fails](https://github.com/userfrosting/UserFrosting/runs/2091554180?check_suite_focus=true#step:16:20) with this error : 

```
Invalid version string "7.2.34-18+ubuntu20.04.1+deb.sury.org+1"  
```

[`VersionParser::normalize`](https://github.com/composer/semver/blob/dd61cb4efbd0cff1700b217faf24ce596af4fc4e/src/VersionParser.php#L102) basically ends as `7.2.34-18` instead of `7.2.34`. 

I know technically it's the PHP version that is at fault here, but this is a common naming scheme from packaged provided PHP on some distro. Even if we were to change our test to go around, the issue would still arise for some users when using this code on their server with this kind of version scheme (and somehow Composer itself doesn't complain about it...?)

**Comment by stof** [comment]
the reason why composer does not complain is because it has a special handling for such weird php versions: https://github.com/composer/composer/blob/b6826f352390b4c952be8fd75d60cfd4f6f39f11/src/Composer/Repository/PlatformRepository.php#L97-L103

This is not something implemented in the `composer/semver` package, because that would allow such weird versioning scheme for all packages out there (thus, that's not semver anymore)

**Comment by stof** [comment]
bote that for your use case about checking only for being higher than a given PHP version, you could do a check on `PHP_VERSION_ID` instead of matching a semver constraint against `phpversion()` and having to deal with cleaning it.

**Comment by lcharette** [comment]
Thanks for the quick reply and pointing me in the right direction. I'll probably got the `PHP_VERSION_ID` or Composer like route.
