### ISSUE TITLE
Bumping patch version by one

### ISSUE THREAD

**Issue by szepeviktor** [composer/semver#137]
Hello! I'd like to use this package for my purposes.

```php
$arbitraryVersion = 'v1.0.2';

echo bump(parse($arbitraryVersion), 3rd number, +1); // 1.0.3
```

Is it possible?
Thanks.

**Comment by Seldaek** [comment]
Not really no. You can VersionParser->normalize then check if you have dots (just in case your version is not numeric) then you can explode on the dots, do $bits[2]++ then implode back and trim any trailing `.0` that you may not be interested in (as normalized format is `a.b.c.d`. 

Manipulation isn't really part of this lib.
