### ISSUE TITLE
Deviation from npm/semver in tilde range constraint

### ISSUE THREAD

**Issue by alcohol** [composer/semver#14]
I noticed that composer/semver treats tilde differently compared to npm/semver:

constraint | composer | npm | same
-------------|--------------|---------|----------
~1 | >=1.0.0 <2.0.0 |  >=1.0.0 <2.0.0 | :white_check_mark:
~1.2 | >=1.2.0 <2.0.0 |  >=1.2.0 <1.3.0 | :x:
~1.2.3 | >=1.2.3 <1.3.0 |  >=1.2.3 <1.3.0 | :white_check_mark:

It is probably too late to change it now. But it is worth noting down perhaps, somewhere.

**Comment by stof** [comment]
it is indeed too late to change it IMO

**Comment by Seldaek** [comment]
For the record ~ in composer is the same as bundler's ~> IIRC. Only with the addition of the other range operators have I tried to follow npm as closely as possible. That explains the discrepancy, but down the line semver does not define any version constraint or operators so yeah we can document changes from npm if that helps but it has no impact on semver.

**Comment by alcohol** [comment]
Yeah I know, it's not even semver related, I didn't mean to imply that. I was just referring to the package because most of the features we (want to) implement are based on or similar to theirs.
