### ISSUE TITLE
Consider following semver.org rules for pre-release and build metadata suffixes

### ISSUE THREAD

**Issue by alcohol** [composer/semver#15]
As written on semver.org:

>  * A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.
>
>  * Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

Do we want to follow these as close to the letter as possible?

**Comment by alcohol** [comment]
Currently we only determine pre-release version info based on the following:

```
[._-]?(?:(stable|beta|b|RC|alpha|a|patch|pl|p)(?:[.-]?(\d+))?)?([.-]?dev)?
```

Note that the hyphen is optional and we only support a select few specific keywords as valid pre-release version strings.

**Comment by naderman** [comment]
We do want to be able to parse as many other common versions as possible, so no, unnecessarily restricting version parsing further is not something we want to do.

**Comment by alcohol** [comment]
But current it actually is more restricted than semver in many ways since we only allow a select few specific keywords rather than just an alphanumeric match. The only flexibility we offer is not requiring a hyphen in front of the pre-release version string.

**Comment by naderman** [comment]
Well we do have the additional constraint that they must be version_compare()'ble

**Comment by alcohol** [comment]
I know we do. But for semver there actually is no special order for pre-release version strings (other than numerical or alphabetic lexical ordering). On top of that, `version_compare` supports the string 'dev' but we do not (not in the same manner at least).

**Comment by alcohol** [comment]
I guess it also comes down to the following question(s).

Should this package retain full BC for Composer? Or are we aiming to create a package that actually follows and applies semantic versioning rules?

**Comment by stof** [comment]
well, the goal of this package is to be used inside Composer itself IMO. What people have been asking many times is being able to reuse the parsing rules of Composer. If we expose a dedicated library but with different rules than composer itself, it will lead to many WTFs (and it will be a pain to document as we would have to document 2 similar yet different behaviors).

**Comment by alcohol** [comment]
Would it be possible to find a middle ground?

Support more than just the pre-release version strings that `version_compare()` supports, but at the same time also allow omitting the hyphen which Composer allows at the moment but semantic versioning does not.

**Comment by stof** [comment]
the issue to support more pre-release version strings than ``version_compare`` supports is that this would require implementing the comparison of versions in userland rather than using ``version_compare``, otherwise pre-release versions would not be sorted properly.

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. 

Using a userland implementation rather than the function implemented in C might have a performance impact on Composer though, which may not be desirable

**Comment by alcohol** [comment]
Well actually you can still use `version_compare()` (it does support random strings), we just have to accept the fact that the order will be

```
any string not found in this list  < dev < alpha = a < beta = b < RC = rc < # < pl = p
```

**Comment by stof** [comment]
@alcohol which is *not* the behavior required by semver, so it would not be compliant

**Comment by alcohol** [comment]
But it would be more of a middle ground than we currently have.

**Comment by stof** [comment]
well, currently we don't support them, and we tell users about it. what you suggest is to accept them but treat them in an incompatible way. This looks worse from a user experience PoV.

**Comment by alcohol** [comment]
What about making this package follow semver, but add an extension/compat layer for Composer?

**Comment by stof** [comment]
@alcohol see my comment in https://github.com/composer/semver/issues/15#issuecomment-127985436

**Comment by alcohol** [comment]
Maybe we should not call it semver then? Or would that be too drastic?

`composer/versioning` or something seems more suitable in that case.

**Comment by Seldaek** [comment]
build metadata is already supported AFAIK. And for pre-release we already support RC/alpha/beta/patch which is already plenty of room to confuse the heck out of people. Allowing arbitrary pre-release IMO brings nothing to the table except making old versioning schemes conform to semver. We don't have them in composer right now so allowing them just means people can start doing stuff that's not recommended. I'd rather not do that, as I don't see any benefit except implementation purity.

Now if it can be done optionally without degrading performance maybe why not but I wouldn't want to enable that in composer.

**Comment by alcohol** [comment]
Well, npm/semver includes a "loose" (boolean) argument for most of their methods. Maybe we could do something like that, and default to false. In true mode, allow more?

**Comment by naderman** [comment]
I think really you need answer Jordi's question of what is the point, why would we make these changes. What we have works, I don't see a reason to change it.

**Comment by alcohol** [comment]
I'm not saying I want to change it. And as also discussed with Jordi on IRC, I will look into how easy it is to implement a loose flag. If it is a minor change, I will submit a PR, if not, we leave things as they are. I do believe that we should at least document / express clearly that we do not follow semantic versioning as described on semver.org to the letter.

**Comment by alcohol** [comment]
I modified #13 to:

  * allow (but ignore) build metadata,
  * allow (but ignore) prefixing a numerical version with a "v",
  * support "r" as an additional modifier (it's the one people most frequently raise issues about).

Is that a middle ground everyone can agree on?

**Comment by Seldaek** [comment]
I wish you hadn't added them to #13 because it mixes concerns even more in that already huge PR.. we don't need to address all issues at once, there is time. Especially for this compliance nitpick :/

But anyway if it's done, metadata/v prefix sure that's fine. The r is that equivalent for RC? If so then I guess yes, but for what it's worth I really wish people would stop doing shit like this. r or a or b is not clear at all, rc is [already too short-hand](https://bbs.archlinux.org/viewtopic.php?id=13052) in a way but at least it's googlable. The rest is just obscure nonsense to anyone not familiar.
