### ISSUE TITLE
get minimum version out of a constriant definition

### ISSUE THREAD

**Issue by staabm** [composer/semver#156]
I wonder whethere there is a way to get a lower bound contraint out of a constraint like `~8.2.0 || ~8.3.2`

my goal is find the minimum php version of a given project so I can utilize this information to make phpstan aware of the possible value range of `PHP_VERSION_ID` - so we can finally catch bugs like https://github.com/Roave/BetterReflection/pull/1406#discussion_r1523065225 via static analysis

**Comment by staabm** [comment]
ohh maybe I created the issue too fast. I just found https://github.com/composer/semver/blob/1d09200268e7d1052ded8e5da9c73c96a63d18f5/src/Constraint/ConstraintInterface.php#L57

**Comment by stof** [comment]
this is indeed what those bound getters are about (be careful to handle properly the special bounds based on `Bound::isZero()` and `Bound::isPositiveInfinity()`)

**Comment by staabm** [comment]
@stof thank you. I am not sure when these special bounds are useful/necessary to check.

could have a look, whether I missed something in `src/Php/ComposerPhpVersionFactory.php`

https://github.com/phpstan/phpstan-src/pull/2968/files#diff-df5d80fc80683bf2ae7389bd56866cefcbf3e5f1d05db296d11133b039f4341a ?

could you give me a example of php version constraint when I need to check for these special bound types and how?

**Comment by stof** [comment]
@staabm those bounds will be used when you define constraints that have no explicit bounds (i.e. `<= 8.6` or `>= 7.4`)

**Comment by stof** [comment]
Based on your own usages of a nullable version in your ComposerPhpVersionFactory, `Bound::isZero` for the lowest bound should make you use `minVersion = null`. And similar for the max version with `Bound::isPositiveInfinity`

**Comment by staabm** [comment]
thank you
