### ISSUE TITLE
simple usage question

### ISSUE THREAD

**Issue by tacman** [composer/semver#169]
How do I find if a version matches a constraint, like

I want to know which versions of Symfony are supported with a constraint like  "^5.4||^6.4"?

```php
        $constraintInComposer = '^5.4||^6.4';
        $c = new Constraint('>=', $versionConstraint);
        foreach (['5.4','6.4','7.0'] as $actualVersion) {
            $match = Semver::satisfies($actualVersion, $c);
            dump("$actualVersion >= $versionConstraint ? " . $c->getPrettyString() . ' ' . ($match?'yes':'no'));
        }
```

I imagine I want to use isSubsetOf, or maybe satisfies(), but I can't figure out how to create the constraint.

I've used PharIo\Version\VersionConstraintParser, but it rejects too many strings that composer accepts (like "php":"^8")

I've read the docs, but I'm missing something basic.  Thanks.

```php
use Composer\Semver\Intervals;

// Checks whether $candidate is a subset of $constraint
Intervals::isSubsetOf(ConstraintInterface $candidate, ConstraintInterface $constraint);

// Checks whether $a and $b have any intersection, equivalent to $a->matches($b)
Intervals::haveIntersections(ConstraintInterface $a, ConstraintInterface $b);
```

**Comment by stof** [comment]
you should use `Composer\Semver\VersionParser`, which has a `parseConstraints` method to object the ConstraintInterface. You can then uses its `matches` method against a constraint specifying an exact match with a (normalized) version.

However, if you don't have special performance needs that require parsing constraints and normalizing versions only once, you can write simpler code by using the static methods of the `Semver` class which expose a higher-level API using directly the string representation of the version and the constraints, performing the parsing internally (and if you do have the performance requirements, looking at the implementation of the Semver class is a good way to see how the lower-level API should be used)

**Comment by tacman** [comment]
Perfect, thanks!  Here's my working code:

```php
        $parser = new VersionParser();
        $versionConstraintString = '^7.4||^8.1';
        $constraint = $parser->parseConstraints($versionConstraintString);
        foreach (['7.3', '7.4.1', '8.0','8.1','8.2'] as $actualVersion) {
            $actualVersionConstraint = $parser->parseConstraints($actualVersion);
            $match = $constraint->matches($actualVersionConstraint);
            dump("$actualVersion >= $versionConstraintString ? " . ($match?'y':'n'));
        }
```
