### ISSUE TITLE
Version comparison fails

### ISSUE THREAD

**Issue by dmolineus** [composer/semver#17]
The implementation of the version comparison of the `Constraint` will fails when using a sub class of `Constraint`.

For instance if a 3rd party code still uses the `Composer\Package\LinkConstraint\VersionConstraint` class which is a subclass. It will fail because the `$provider->version` property is private and is only accessible from the `Constraint` class itself.

https://github.com/composer/semver/blob/5356567e1c08e10998aac6e385a38c7a8f163437/src/Constraint/Constraint.php#L159

Related issue contao-community-alliance/composer-plugin/issues/44.

**Comment by alcohol** [comment]
So we should make the classes `final` ?

**Comment by dmolineus** [comment]
What would you do with https://github.com/composer/composer/blob/master/src/Composer/Package/LinkConstraint/VersionConstraint.php in that case?

**Comment by alcohol** [comment]
It was a question, not a suggestion. I personally don't see a need to make them `final`, nor do I see an issue.

The file you linked was explicitly left behind to make people aware of the changes and hopefully trigger them to fix their code and use the new implementation.

**Comment by dmolineus** [comment]
I know that the class is left behind as fallback. Unfortunately it does not work with the current implementation. So there is already a break. 
I suggest to declare the `version` property as protected in `Composer\Package\LinkConstraint\VersionConstraint`. Then it'll work again.

**Comment by alcohol** [comment]
Yes. There is another issue we are investing though. I want to first see if that needs resolving as well. Because afterwards we will need to update the lock file of composer to propagate the changes. Will get back to you asap.

**Comment by stof** [comment]
@dmolineus Constraint code is allowed to access a Constraint private property even if the object is actually a child AFAIK (code written in the child class would not be allowed to do it).

What is the error you are getting ?

**Comment by alcohol** [comment]
@stof is right.

Unless I misunderstood...

```
rob@macbookpro /srv/git/github/composer (master) $ cat compare.php
<?php

require __DIR__.'/vendor/autoload.php';

$a = new Composer\Semver\Constraint\Constraint('==', '1.2.3');
$b = new Composer\Package\LinkConstraint\VersionConstraint('==', '1.2.3');

var_dump(
    $a->matchSpecific($b),
    $b->matchSpecific($a)
);

rob@macbookpro /srv/git/github/composer (master) $ php compare.php
bool(true)
bool(true)
```

**Comment by dmolineus** [comment]
Sorry, i got it wrong. Of course, you are right. The issue is that the version comparison fails when using the deprecated class. Looked again at it, here's the issue: 

https://github.com/composer/semver/blob/5356567e1c08e10998aac6e385a38c7a8f163437/src/Constraint/AbstractConstraint.php#L34

It works only in one direction, see:

```

```

**Comment by alcohol** [comment]
But that is not the case here, since they both inherit from the abstract class.

```
rob@macbookpro /srv/git/github/composer (master) $ cat compare.php
<?php

require __DIR__.'/vendor/autoload.php';

$a = new Composer\Semver\Constraint\Constraint('==', '1.2.3');
$b = new Composer\Package\LinkConstraint\VersionConstraint('==', '1.2.3');

var_dump(
    $a->matches($b),
    $b->matches($a)
);
rob@macbookpro /srv/git/github/composer (master) $ php compare.php
bool(true)
bool(true)
```

**Comment by alcohol** [comment]
Actually, the `$b->matches($a)` reaches the implict `return true` branch in the `matches()` implementation.

/cc @naderman any idea why that branch is there? How is this supposed to work? What was the idea here? Can we change it to `instanceof AbstractConstraint`? It would also mean we can implicitly define the method on the interface, which is commented right now.

**Comment by naderman** [comment]
@alcohol sorry can you point to specific lines, not sure which branch you mean?

**Comment by alcohol** [comment]
@naderman sure, https://github.com/composer/semver/blob/master/src/Constraint/AbstractConstraint.php#L39

**Comment by alcohol** [comment]
`$a->matches($b)` ends up going through `matchSpecific()` cause the instanceof comparison evaluates to true. But for `$b->matches($a)` it evaluates to false and we just return true without actually comparing anything.

**Comment by naderman** [comment]
@alcohol I think originally we expected to have more constraint types than we ended up with, and each constraint type was only supposed to be comparable to another constraint of the same type? Anyway this code doesn't seem to make too much sense the way it works today. We don't really have multiple constraint types anyway anymore, so that could probably all be refactored anyway? Not even sure why we have an AbstractConstraint at all anymore?

**Comment by alcohol** [comment]
Eh I honestly have no idea either. This code predates my involvement.

/cc @Seldaek @stof any idea?

**Comment by stof** [comment]
Well, we have 3 implementations of ConstraintInterface, and only 1 of them is extending AbstractConstraint. I think the abstract constraint should be removed entirely. We should instead implement ``Constraint::matches`` directly.

**Comment by alcohol** [comment]
I've come to the same conclusion so far. I think the matchSpecific can just be merged with matches in Constraint.
