### ISSUE TITLE
Add high level library functions

### ISSUE THREAD

**Issue by Seldaek** [composer/semver#2]
Some inspiration can be found at https://github.com/npm/node-semver#functions - I think it'd be nice to have a more comprehensive toolkit than version_compare in PHP. We have all the underlying code just needs to be made a bit more usable as a wrapper class or something.

**Comment by legoktm** [comment]
Here are the functions that npm has under "compare":
- [ ] valid
- [ ] increment
- [ ] major
- [ ] minor
- [ ] patch
- [ ] gt
- [ ] gte
- [ ] lt
- [ ] lte
- [ ] eq
- [ ] neq
- [ ] cmp
- [ ] compare
- [ ] rcompare
- [ ] diff

I'll take a stab at implementing some of them.
