### ISSUE TITLE
Composer\Sermver\Constraint when require == 1, provide == 1.0

### ISSUE THREAD

**Issue by ikappas** [composer/semver#30]
Not sure if this is a bug but the following will fail:
```php
        $versionRequire = new Constraint('==', '1');
        $versionProvide = new Constraint('==', '1.0');

        $this->assertTrue($versionRequire->matches($versionProvide));
```
this happens due to php's version_compare function evaluating 1 < 1.0 < 1.0.0

**Comment by stof** [comment]
this is why Composer has a way to normalize version. Constraints should be built with normalized versions, not pretty versions.

**Comment by ikappas** [comment]
@stof Thank you for your clarification. I stumbled upon this while porting the lib to ruby and though I ask

**Comment by alcohol** [comment]
If you are porting this to make a `semver` library for ruby then I would caution you that this library actually does not follow `semver` in some regards. There are some deviations and quirks which might or might not be documented.

**Comment by ikappas** [comment]
@alcohol Hi and thanks for the heads up.

I ported [php-composer-semver](https://github.com/ikappas/php-composer-semver) to be used with the [php-composer](https://github.com/ikappas/php-composer) partial port for usage in server side scenario and more specifically my Gitlab [composer-service](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1921) MR for compatibility and interoperability.
