### ISSUE TITLE
Can't handle version numbers of the form "x.y.z-pre1"

### ISSUE THREAD

**Issue by djmattyg007** [composer/semver#45]
Could this be handled by making `pre` an alias of `RC`? It seems to be the intention wherever I see it used.

**Comment by alcohol** [comment]
Why not just use rc..? :-)

**Comment by djmattyg007** [comment]
I'm parsing version numbers that I didn't create.

**Comment by Seldaek** [comment]
Sorry but we are not going to support everything someone made up somewhere.. it's just not the goal of this lib. We want semver support and a few other intricacies for historical reasons, but that's about it.
