### ISSUE TITLE
About "~" operator

### ISSUE THREAD

**Issue by jaschweder** [composer/semver#46]
Hi, some noob doubt about the "~" operator, it need to consider the bugfix level ? for example:

~1.3.1: **>=1.3.1.0-dev** <2.0.0.0-dev

Or only consider the second level ?

~ 1.3.1: **>=1.3.0.0-dev** < 2.0.0.0-dev

**Comment by alcohol** [comment]
Read https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators for details and about the differences between `~` and `^`.

**Comment by GrahamCampbell** [comment]
https://github.com/composer/semver/blob/master/tests/VersionParserTest.php#L295-L313
