### ISSUE TITLE
Pre release; any alpha character after the first segment considered Invalid

### ISSUE THREAD

**Issue by upake** [composer/semver#58]
1.0.0-x.7.z.92 is not recognised as a valid version. But based on the spec this is legal. 

Based on https://semver.org/

A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

**Comment by Seldaek** [comment]
Indeed we do not follow the spec 100% due to some internal constraints to work with Composer and PHP. That's not going to be fixed however.

**Comment by alcohol** [comment]
See also https://github.com/composer/semver/blob/master/tests/VersionParserTest.php#L96
