### ISSUE TITLE
Please include the test suite with the releases

### ISSUE THREAD

**Issue by orlitzky** [composer/semver#59]
Hi, we have a Gentoo package for semver and would like our users to be able to run the test suite when they install it to catch unexpected incompatibilities. But we install the release tarballs (they use less space, can be gpg signed, don't require git as a build dependency, etc), and the releases don't have the tests in them.

Would you consider adding them? Thanks!

**Comment by alcohol** [comment]
I don't think this will happen. It is intentionally excluded from the release tarball because there is no purpose for tests in a production environment. If someone wants to run tests to check for incompatibilities, they should use the development release (git clone).
