### ISSUE TITLE
Any plans to pull "best match" functionality down to this package?

### ISSUE THREAD

**Issue by mdwheele** [composer/semver#6]
My rough understanding of Composer internals related to SAT solving is that it registers multiple pools of providers and based on requirements and a voodoo dance, determines a set of "best matching" providers that meet satisfiability requirements of the requiring package.

My question is whether or not some of this logic might make its way down to this package. I am just curious because I'm currently having to maintain a minimal implementation of this for another project and am so excited to see semver pulled out like this! Anywho, fully understand if that would be considered "out of scope" for this package, but was just curious if there were plans for that or if the project would be open to even splitting that out as another separate component. 

Sorry for rambling :smile:  

Thanks for all you folks do!

**Comment by alcohol** [comment]
I don't think the solver belongs in this package. It serves a very different purpose. It might make use of this package, but it doesn't belong here. As for whether or not the solver will ever be split off from Composer core, I don't know :-).

**Comment by legoktm** [comment]
+1, I think if the solver was split out of composer, it should end up in a separate library.

**Comment by Seldaek** [comment]
Best match style things for now rely on the pool but that will hopefully change with https://github.com/composer/composer/pull/4163 and then extracting that functionality might be possible. Until then though it's best to rely on composer itself as dependency if you need this sort of thing, or just rely on a version_compare to sort versions.

**Comment by mdwheele** [comment]
Fair enough! Thanks guys!
