### ISSUE TITLE
Does Semver::satisfies work properly?

### ISSUE THREAD

**Issue by mikbox74** [composer/semver#60]
Hello!
I used `Semver::satisfies($v, $version)` for checking and got this:

joomla/input: ~1.2|~2.0 satisfied by 1.2.1
**joomla/filter: ~1.0 satisfied by 1.3.3**
**joomla/string: ~1.3|~2.0 satisfied by 1.4.1**
joomla/registry: ^1.4.5|~2.0 satisfied by 1.6.0
**joomla/compat: ~1.0 satisfied by 1.2.0**
joomla/utilities: ^1.4.1|~2.0 satisfied by 1.5.0
**symfony/polyfill-php55: ~1.0 satisfied by v1.7.0**
ircmaxell/password-compat: ~1.0 satisfied by v1.0.4
psr/log: ~1.0 satisfied by 1.0.2

I'm newbie in this theme but I guess this list contains errors. It's strange, seems `~` behaves like `^`. May be I must use some additional shecking or some additional parameters?

**Comment by GrahamCampbell** [comment]
> It's strange, seems ~ behaves like ^. 

Yes, the two are identical, apart from when it comes to parsing 0.x series versions.

**Comment by mikbox74** [comment]
Can I get Composer-like update checking by filtering list with `Semver::satisfies`+`VersionParser::parseStability`+`Composer\DependencyResolver\Pool::isPackageAcceptable` then getting greatest version from this list?

**Comment by alcohol** [comment]
How the constraints work is explained here:

https://getcomposer.org/doc/articles/versions.md

As for your question, no, that will not tell you much other than if the package satisfies the given constraint or not. That is not Composer-like update checking.

**Comment by mikbox74** [comment]
@GrahamCampbell , @alcohol Thank you for answers! In addition I found an useful service: https://semver.mwl.be , it helped me to debug my checker.

@alcohol can I find anywhere a detailed explanation for the Comoser update checking logic?

**Comment by alcohol** [comment]
Only in the source code.
