### ISSUE TITLE
Comparator::equalTo return false when compare two constraints.

### ISSUE THREAD

**Issue by Maurisss94** [composer/semver#63]
Hi, i need to check if two versions constraints `5.7.*` are equal, and not want to do with comparator `===`.

But my surprirse is, when i check this line `Comparator::equalTo($this->composer['require'][$dependency], $version)`, the result is false, but the two strings are `5.7.*`.

Somebody can help me?

**Comment by stof** [comment]
`5.7.*` is a version constraint, not a version. The Comparator class is about comparing versions.

**Comment by Maurisss94** [comment]
And what class should be use, to compare constraints?

**Comment by Maurisss94** [comment]
Sure, it makes a lot of sense.
I wanted to compare both versions and constraints between two composer.json files, and pick up the package with the newest version.
I will use the equality comparer `==`, for constraints and the Comparator class for versions.

Thank you.

**Comment by alcohol** [comment]
The only thing you could compare between constraints is their upper and lower boundaries. Comparing the constraints themselves does not make much sense as @stof said because they represent a range.

**Comment by stof** [comment]
> The only thing you could compare between constraints is their upper and lower boundaries.

even that may not always work fine, as constraints don't represent *one* range, but a union of ranges (due to the `||` operator)
