### ISSUE TITLE
Package phpunit/phpunit-mock-objects is abandoned

### ISSUE THREAD

**Issue by rodrigoaguilera** [composer/semver#66]
Composer install is giving me a warning about this package because it depends on an abanadoned library
https://packagist.org/packages/phpunit/phpunit-mock-objects

Is there plans to replace it?

**Comment by stof** [comment]
This should be asked to the maintainers of the package, not to the composer team.

**Comment by stof** [comment]
In this case, I think the latest version of PHPUnit does not depend on it anymore because the feature was moved back to PHPUnit itself.

**Comment by alcohol** [comment]
Not sure why we specifically have this extra requirements. Perhaps to enforce a minimum version? Because phpunit also requires it as well. So in theory we should already pull it in when we depend on phpunit alone.

**Comment by yuceltoluyag** [comment]
Please note that PHPUnit 7 is only supported until February 7, 2020. Also note that PHP 7.1 is no longer actively supported. https://phpunit.de/supported-versions.html

```
 "require-dev": {
        "phpunit/phpunit": "^7"
    }
```

**Comment by alcohol** [comment]
Please note that Semver is part of Composer and we still officially support PHP 5.3 and up.

**Comment by GrahamCampbell** [comment]
I don't think it matters that the package is abandoned? So is PHP 5, however we want to support that too.

**Comment by rodrigoaguilera** [comment]
I think this issue should have a couple of followups. A plan to raise the php requirement and then based on the minimum php version required update the phpunit version.

What do you think?

**Comment by alcohol** [comment]
No need. This will happen eventually when Composer implements new requirements.

**Comment by DonRichards** [comment]
I'm sorry but I don't follow. phpunit/phpunit is currently being developed but **phpunit/phpunit-mock-objects** is deprecated and is no longer receiving any updates. phpunit/phpunit-mock-objects is currently being required by this module. @yuceltoluyag are you suggesting this module is also not expected to receive development any further due to the PHPUnit 7 end-of-life in February of 2020?

**Comment by stof** [comment]
@DonRichards phpunit-mock-objects is not a requirement of this module. It might get installed depending on which phpunit version is selected (due to composer 1.x being compatible with PHP 5.3+, the testsuite may need to use old PHPUnit releases to run tests on old PHP versions).

**Comment by stof** [comment]
@alcohol it looks like the change you made in April has never been released.

**Comment by DonRichards** [comment]
@stof 1.5.0 is the latest Tag in this repo. If they rely on tags that's probably the issue.

**Comment by alcohol** [comment]
I think we haven't tagged a new release because feature wise nothing has changed yet since 1.5. Do you think the new requirements warrant a release/tag?

**Comment by stof** [comment]
if this was a requirement, it could. Given that this is only a dev requirement, this is fine IMO (as it has no impact on projects using composer/semver).

**Comment by alcohol** [comment]
Will leave it as-is for now then :+1:
