### ISSUE TITLE
Doubts on Semver comparison  for versions like a.b.x-dev

### ISSUE THREAD

**Issue by lcwj3** [composer/semver#70]
I am trying to use satisfiedBy to parse php dependencies, somehow I found an error like this:
```
library name: aarontong00/zippy
version:1.3
```
the dependencies of this library version is:
```
php: >=5.5
doctrine/collections: v1.4.0
symfony/filesystem: ^2.0.5 || ^3.0
symfony/process: ^2.1 || ^3.0 || ^4.0
symfony/polyfill-mbstring: ^1.3
```
For all versions of symfony/filesystem, I parsed the deps like this:
```
function check($req, $v)
{
    $satisfies = array();
    $vers = explode('|', $v);
    $satisfies = Semver::satisfiedBy($vers, $req);
    echo implode('|', $satisfies);
}
check('^2.0.5 || ^3.0', '3.3.x-dev|3.4.x-dev|3.4.32|dev-1');
```
The output is `3.3.x-dev|3.4.x-dev|3.4.32`
but when I used composer update to install this aarontong00/zippy:1.3, the installed version of 
 symfony/filesystem is 3.4.32. So I think the output of satisfiedBy shouldn't include the 
dev versions if the dev tags are not considered when install.

**Comment by stof** [comment]
dev branches are satisfying the constraint. But by default, the composer solver excludes dev versions (due to `minimum-stability` being `stable` by default).

**Comment by lcwj3** [comment]
Thanks for you kind and quick reply. So does this means I need to filter out stable versions before I parse the deps?  Is there any other tool I can use to do this? Thank you very much!

**Comment by stof** [comment]
Well, I don't know what you are trying to achieve, so I cannot tell you what you should do to achieve it.

**Comment by Seldaek** [comment]
You can easily exclude them using VersionParser::parseStability, keeping only 'stable' ones or whatever you are interested in.

**Comment by lcwj3** [comment]
So sorry for late reply, actually I am trying to build a dependency graph for php packages, that is why I need to parse the dependencies accurately, will try the VersionParser::parseStability, thank both of you so much! Will close this issue now.
