### ISSUE TITLE
Version `1.0.*-stable` gives error

### ISSUE THREAD

**Issue by mitelg** [composer/semver#77]
Hello there :wave: 

If I try to test the version `1.0.*-stable` with `Semver::satisfies` the following error shows up:

> [UnexpectedValueException] Could not parse version constraint 1.0.\*-stable: Invalid version string "1.0.*-stable" 

Every other constraint seems to work. Am I doing something wrong or is this a bug? 

Best regards

**Comment by alcohol** [comment]
Looking at https://github.com/composer/semver/blob/39da74948fd424cf0e8321b96f04c2a1b2480a15/src/VersionParser.php#L396-L420, I do not think that is a constraint we support.

**Comment by alcohol** [comment]
But it seems to me that using `^1.0-stable` should achieve what you are looking for.

**Comment by alcohol** [comment]
@Seldaek do you recall why the wildcard constraint type might not support stabilities?

**Comment by Seldaek** [comment]
composer/semver itself has no concept of allowed stabilities for a given range. `1.0.*-stable` means nothing to it, and `1.0.*` includes everything from 1.0.0-dev to 1.9999... and in the middle you can find 1.5.3-alpha.

In composer you'd have to say `1.0.*@stable` to force it to ignore non-stable versions.

If you're using this library directly, I guess you'd need to parse the stability of the version you are checking against and see if it is stable, and if yes then check if it satisfies the constraint.

**Comment by mitelg** [comment]
my use case is, that I have a bunch of versions `['1.0.0', '1.0.1', '1.0.0-RC1', '1.0.0-RC2']` which I test agains a version constraint extracted from a `composer.json` file. Which could be `~1.0.0` or `1.0.*` or what ever composer supports. I also read out `minimum-stability` and use `VersionParser::parseStability` to get the stability. I then put it together with the version, so it looks like this: `~1.0.0stable`. Giving this to `Semver::satisfiedBy` I get the supported versions back. 

Is this the right approach? or should I use something else to get supported versions?

**Comment by Seldaek** [comment]
As I said, I think the versions should first be filtered based on the allowed stability (either minimum-stability, or stability flag like `@dev`, `@stable`, etc.), then passed through satisfiedBy

**Comment by mitelg** [comment]
ok, thanks for your help :blush: :+1:
