### ISSUE TITLE
[Suggestion] Rename EmptyConstraint to MatchAllConstraint

### ISSUE THREAD

**Issue by stof** [composer/semver#90]
The name `EmptyConstraint` is quite confusing. This is a match-all constraint, so the set of matched versions is not empty at all. And its string representation is not empty either (as that's `*`).

Of course, we will need to keep a deprecated EmptyConstraint child class for BC.

**Comment by Seldaek** [comment]
Sounds good to me. @naderman any concerns?

**Comment by naderman** [comment]
Sounds good!

**Comment by Seldaek** [comment]
If anyone wants to PR this feel free then, otherwise I'll get to it later this week I guess.
